version: "3.9"

services:
  pg_db:
    container_name: pg_db
    image:
      postgres:14.7-alpine
    volumes:
      - pg_data:/var/lib/postgresql/data/
    restart: always
    environment:
      POSTGRES_PASSWORD: ${DATABASE_PASS}
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_DB: ${DATABASE_NAME}

  daphne:
    container_name: air_service_daphne
    build:
      context: ./
      dockerfile: Dockerfile.prod
    expose:
      - 8000
    environment:
      DJANGO_SETTINGS_MODULE: air_service.settings
      DATABASE_NAME: ${DATABASE_NAME}
      DATABASE_USER: ${DATABASE_USER}
      DATABASE_PASS: ${DATABASE_PASS}
      DATABASE_HOST: ${DATABASE_HOST}
      CELERY_BROKER: redis://redis:6379/0
      CELERY_BACKEND: redis://redis:6379/0
    entrypoint: /usr/src/air_service/entrypoint.prod.sh
    volumes:
      - .:/usr/src/air_service
    env_file:
      - ./.env
    depends_on:
      - pg_db

  nginx:
    build: ./nginx
    volumes:
      - etc-letsencrypt:/etc/letsencrypt
      - ./nginx/ssl-dhparams.pem:/etc/ssl/certs/dhparam.pem
    ports:
      - 80:80
      - 443:443
    depends_on:
      - daphne

  celery-worker:
    restart: on-failure
    build:
      context: ./
    command: sh -c 'sleep 5 && celery -A air_service worker -l info -P eventlet'
    volumes:
      - .:/usr/src/app
    depends_on:
      - daphne
      - redis

  celery-beat:
    restart: on-failure
    build:
      context: ./
    command: sh -c 'sleep 5 && celery -A air_service beat -l INFO'
    volumes:
      - .:/usr/src/app
    depends_on:
      - daphne
      - redis

  redis:
    image: redis
    container_name: redis
    restart: always
    ports:
      - "6379:6379"

  certbot:
    image: certbot/certbot
    container_name: certbot
    volumes:
      - ./letsencrypt:/etc/letsencrypt
      - ./nginx/ssl-dhparams.pem:/etc/ssl/certs/dhparam.pem
      - www-html:/var/www/html
#    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done'"
    command: certonly --webroot --webroot-path=/var/www/html --email rollbar1990@gmail.com --agree-tos --no-eff-email --staging -d django-air-foxstudent101801.pp.ua www.django-air-foxstudent101801.pp.ua
    depends_on:
      - nginx

volumes:
  pg_data:
  letsencrypt:
